version: "3.7"
services:
  app:
    image: eclipse-temurin:17.0.6_10-jdk
    volumes:
      - ./app/build/libs/app-1.0-SNAPSHOT-all.jar:/app/app.jar
    command: java -jar /app/app.jar
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.37.6
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
